version: "3.1"
services:
  postgresdb:
    build: ./postgres
    ports:
      - "6002:5432"
    environment:
      POSTGRES_USER: "demo"
      POSTGRES_PASSWORD: "demo"
      POSTGRES_DB: "demodb"
    volumes:
      - "./postgres/sql:/docker-entrypoint-initdb.d"
      - db:/var/lib/postgresql/data

volumes:
  db: {}
